#***************************************
#SELENIUM HUB
#***************************************
apiVersion: v1
kind: Service
metadata:
  name: selenium-hub
  labels:
    name: selenium-hub
    component: "selenium-grid"
spec:
  selector:
    app: selenium-hub
  ports:
    - name: web
      protocol: TCP
      port: 4444
      targetPort: 4444
      nodePort: 30001
    - port: 4442
      targetPort: 4442
      name: port2
    - port: 4443
      targetPort: 4443
      name: port3
  type: NodePort
  sessionAffinity: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-hub-deployment
  labels:
    app: selenium-hub
    name: selenium-hub
    component: "selenium-grid"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-hub
  template:
    metadata:
      labels:
        app: selenium-hub
        name: selenium-hub
        component: "selenium-grid"
    spec:
      containers:
        - name: selenium-hub
          image: selenium/hub:4.9.1
          env:
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: "4442"
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: "4443"
          ports:
            - containerPort: 4444
              protocol: TCP
---
#***************************************
#SELENIUM CHROME NODE
#***************************************
apiVersion: v1
kind: Service
metadata:
  name: selenium-chrome-node
  labels:
    name: selenium-chrome-node
    component: "selenium-grid-4"
spec:
  selector:
    app: selenium-chrome-node
  ports:
    - name: port1
      protocol: TCP
      port: 6900
      targetPort: 5900
    - name: port2
      protocol: TCP
      port: 5553
      targetPort: 5553
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-chrome-node-deployment
  labels:
    app: selenium-chrome-node
    name: selenium-chrome-node
    component: "selenium-grid-4"
spec:
  replicas: 5
  selector:
    matchLabels:
      app: selenium-chrome-node
  template:
    metadata:
      labels:
        app: selenium-chrome-node
        name: selenium-chrome-node
        component: "selenium-grid-4"
    spec:
      restartPolicy: Always
      containers:
        - name: selenium-chrome-node
          image: selenium/node-chrome:111.0
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
          ports:
            - containerPort: 5553
              protocol: TCP
          resources:
            requests:
              memory: "128Mi"
              cpu: "1"
            limits:
              memory: "1Gi"
              cpu: "8"
          env:
            - name: START_XVFB
              value: "true"
            - name: SE_NODE_GRID_URL
              value: "http://localhost:30001/"
            - name: SE_NODE_SESSION_TIMEOUT
              value: "64800"
            - name: SE_EVENT_BUS_HOST
              value: "selenium-hub"
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: "4442"
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: "4443"
            - name: SE_NODE_MAX_INSTANCES
              value: "10"
            - name: SE_NODE_MAX_SESSIONS
              value: "10"
      volumes:
        - name: dshm
          emptyDir: { "medium": "Memory" }